[workspace]
authors = ["Jakob Lass <jakob.lass@psi.ch>"]
channels = ["conda-forge"]
name = "MJOLNIR"
platforms = ["win-64"]
version = "1.4.0"

[tasks]
lab = "jupyter lab"
test = "pytest"

# ---------------------------------------------------------------------------
# Common dependencies
# ---------------------------------------------------------------------------

[dependencies]
pytest = ">=7,<10"
h5py = ">=3.8,<4"
regex = ">=2025.0,<2027"
pandas = ">=2,<4"
future = ">=1,<2"
sympy = ">=1.14,<2"

# ---------------------------------------------------------------------------
# Python versions
# ---------------------------------------------------------------------------

[feature.py39.dependencies]
python = "3.9.*"

[feature.py312.dependencies]
python = "3.12.*"


# ---------------------------------------------------------------------------
# NumPy / SciPy versions
# ---------------------------------------------------------------------------

[feature.numpy1.dependencies]
numpy = ">=1.26,<2"
scipy = ">=1.10,<1.18"

[feature.numpy2.dependencies]
numpy = ">=2,<3"
scipy = ">=1.18,<2"


# ---------------------------------------------------------------------------
# Matplotlib / pyqtgraph versions
# ---------------------------------------------------------------------------

[feature.legacy-plot.dependencies]
matplotlib = ">=3.7,<3.9"

[feature.current-plot.dependencies]
matplotlib = ">=3.11,<4"

[feature.pyqtgraph-legacy.dependencies]
pyqtgraph = ">=0.13,<0.14"

[feature.pyqtgraph-current.dependencies]
pyqtgraph = ">=0.14,<1"

# ---------------------------------------------------------------------------
# Build dependencies
# ---------------------------------------------------------------------------
[feature.build.pypi-dependencies]
build = ">=1,<2"

# ---------------------------------------------------------------------------
# Qt versions
# ---------------------------------------------------------------------------

[feature.qt5.dependencies]
pyqt = ">=5.15,<6"

[feature.qt6.dependencies]
pyqt6 = ">=6,<7"


# ---------------------------------------------------------------------------
# Environments
# ---------------------------------------------------------------------------

[environments]

py39 = [
    "py39",
    "numpy1",
    "legacy-plot",
    "build",
]

py312 = [
    "py312",
    "numpy2",
    "legacy-plot",
    "build",
]

py39-qt5 = [
    "py39",
    "numpy1",
    "legacy-plot",
    "pyqtgraph-legacy",
    "qt5",
    "build",
]

default = [
    "py312",
    "numpy2",
    "current-plot",
    "pyqtgraph-current",
    "qt6",
    "build",
]