#!/bin/bash
source activate CAMEA
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for f in $DIR/*.py; do python "$f"; done
rm -rf .cache
rm -rf .pytest_cache
rm -rf __pycache__
